package io.github.douira.glsl_transformer.ast.print;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import io.github.douira.glsl_transformer.ast.node.Identifier;
import io.github.douira.glsl_transformer.ast.node.expression.*;
import io.github.douira.glsl_transformer.ast.node.expression.binary.*;

import io.github.douira.glsl_transformer.ast.typing.NumericType;
import io.github.douira.glsl_transformer.test_util.TestWithSingleASTTransformer;

public class ASTPrinterTest extends TestWithSingleASTTransformer {
  @Test
  void testOperatorPrecedencePrinting1() {
    p.setTransformation((tree, root) -> {
      root.replaceReferenceExpressions(
          p, "b", "c + d");
    });
    assertTransform(
        "int x = a * (c + d); ",
        "int x = a * b;");
    assertTransform(
        "int x = a + c + d; ",
        "int x = a + b;");
    assertTransform(
        "int x = a | c + d; ",
        "int x = a | b;");
    assertTransform(
        "int x = (c + d)++; ",
        "int x = b++;");
    assertTransform(
        "int x = ++(c + d)++; ",
        "int x = ++b++;");
    assertTransform(
        "int x = ++(c + d); ",
        "int x = ++b;");
  }

  @Test
  void testOperatorPrecedencePrinting2() {
    p.setTransformation((tree, root) -> {
      root.replaceReferenceExpressions(
          p, "b", "++c");
    });
    assertTransform(
        "int x = ++++c; ",
        "int x = ++b;");
    assertTransform(
        "int x = (++c)++; ",
        "int x = b++;");
    assertTransform(
        "int x = (++c)++; ",
        "int x = b++;");
    assertTransform(
        "int x = a + ++c; ",
        "int x = a + b;");
    assertTransform(
        "int x = a + (++c)++; ",
        "int x = a + b++;");
  }

  @Test
  void testOperatorPrecedencePrinting3() {
    p.setTransformation((tree, root) -> {
      root.replaceReferenceExpressions(
          p, "b", "c, d");
    });
    assertTransform(
        "int x = ++(c, d); ",
        "int x = ++b;");
    assertTransform(
        "int x = ++(c, d); ",
        "int x = ++(b);");
    assertTransform(
        "int x = (a, c, d); ",
        "int x = (a, b);");
  }

  @Test
  void testOperatorPrecedencePrinting4() {
    p.setTransformation((tree, root) -> {
      root.replaceReferenceExpressions(
          p, "b", "(c + d)");
    });
    assertTransform(
        "int x = a * (c + d); ",
        "int x = a * b;");
    assertTransform(
        "int x = a * (c + d); ",
        "int x = a * (b);");
  }

  @Test
  void testPrintHeader() {
    p.setTransformation((tree, root) -> {
      tree.outputOptions.enablePrintInfo();
    });
    assertTransform(
        "#version 440 core\n// Generated by glsl-transformer\nint a = 4; ",
        "#version 440 core\nint a = 4;");
  }

  @Test
  void testHeaderSuffix() {
    p.setTransformation((tree, root) -> {
      tree.outputOptions.setHeaderSuffix("/* test */");
    });
    assertTransform(
        "#version 440 core\n// Generated by glsl-transformer /* test */\nint a = 4; ",
        "#version 440 core\nint a = 4;");
  }

  private static ReferenceExpression ref(String name) {
    return new ReferenceExpression(new Identifier(name));
  }

  @Test
  void testEqualityInRelationalOperandIsWrapped() {
    // equality binds less tightly than the relational operators, a nested
    // equality expression needs parentheses to survive a reprint
    Expression nestedRight = p.supplyRoot().indexNodes(
        () -> new LessThanExpression(ref("a"), new EqualityExpression(ref("b"), ref("c"))));
    assertEquals("a < (b == c)", ASTPrinter.printSimple(nestedRight));

    Expression nestedLeft = p.supplyRoot().indexNodes(
        () -> new GreaterThanEqualExpression(new InequalityExpression(ref("a"), ref("b")), ref("c")));
    assertEquals("(a != b) >= c", ASTPrinter.printSimple(nestedLeft));

    // the other way around no parentheses are necessary
    Expression relationalInEquality = p.supplyRoot().indexNodes(
        () -> new EqualityExpression(new LessThanExpression(ref("a"), ref("b")), ref("c")));
    assertEquals("a < b == c", ASTPrinter.printSimple(relationalInEquality));
  }

  @Test
  void testLiteralsOfAllTypesReparse() {
    for (var type : NumericType.values()) {
      if (!type.isScalar()) {
        continue;
      }
      if (!type.hasLiteral()) {
        // literals of the 8 bit integer types cannot be printed since there is no
        // syntax for them, they are rejected when they are constructed
        assertThrows(IllegalArgumentException.class, () -> new LiteralExpression(type, 1));
        continue;
      }

      var literal = switch (type.getNumberType()) {
        case BOOLEAN -> new LiteralExpression(true);
        case SIGNED_INTEGER, UNSIGNED_INTEGER -> new LiteralExpression(type, 42);
        case FLOATING_POINT -> new LiteralExpression(type, 1.5);
      };
      var printed = ASTPrinter.printSimple(literal);
      var parsed = (LiteralExpression) p.parseExpression(p.supplyRoot(), printed);
      assertSame(type, parsed.getNumericType(), printed);
      assertEquals(literal.getNumber(), parsed.getNumber(), printed);
    }
  }
}
