// Builtin definitions for the type analysis, see BuiltinRegistry for the format.
// Lines starting with @ begin a section and list the conditions under which the
// declarations of the section are available.
// ---- 8.9.1 texture query functions
@ glsl>=130 es>=300 ext:GL_EXT_gpu_shader4
int textureSize(gsampler1D sampler, int lod);
ivec2 textureSize(gsampler2D sampler, int lod);
ivec3 textureSize(gsampler3D sampler, int lod);
ivec2 textureSize(gsamplerCube sampler, int lod);
ivec2 textureSize(gsampler1DArray sampler, int lod);
ivec3 textureSize(gsampler2DArray sampler, int lod);
ivec3 textureSize(gsamplerCubeArray sampler, int lod);
ivec2 textureSize(gsampler2DRect sampler);
int textureSize(gsamplerBuffer sampler);
ivec2 textureSize(gsampler2DMS sampler);
ivec3 textureSize(gsampler2DMSArray sampler);
int textureSize(sampler1DShadow sampler, int lod);
ivec2 textureSize(sampler2DShadow sampler, int lod);
ivec2 textureSize(samplerCubeShadow sampler, int lod);
ivec2 textureSize(sampler1DArrayShadow sampler, int lod);
ivec3 textureSize(sampler2DArrayShadow sampler, int lod);
ivec3 textureSize(samplerCubeArrayShadow sampler, int lod);
ivec2 textureSize(sampler2DRectShadow sampler);

@ glsl>=400 es>=320 ext:GL_ARB_texture_query_lod
vec2 textureQueryLod(gsampler1D sampler, float P);
vec2 textureQueryLod(gsampler2D sampler, vec2 P);
vec2 textureQueryLod(gsampler3D sampler, vec3 P);
vec2 textureQueryLod(gsamplerCube sampler, vec3 P);
vec2 textureQueryLod(gsampler1DArray sampler, float P);
vec2 textureQueryLod(gsampler2DArray sampler, vec2 P);
vec2 textureQueryLod(gsamplerCubeArray sampler, vec3 P);
vec2 textureQueryLod(sampler1DShadow sampler, float P);
vec2 textureQueryLod(sampler2DShadow sampler, vec2 P);
vec2 textureQueryLod(samplerCubeShadow sampler, vec3 P);
vec2 textureQueryLod(sampler1DArrayShadow sampler, float P);
vec2 textureQueryLod(sampler2DArrayShadow sampler, vec2 P);
vec2 textureQueryLod(samplerCubeArrayShadow sampler, vec3 P);

@ ext:GL_ARB_texture_query_lod
vec2 textureQueryLOD(gsampler1D sampler, float P);
vec2 textureQueryLOD(gsampler2D sampler, vec2 P);
vec2 textureQueryLOD(gsampler3D sampler, vec3 P);
vec2 textureQueryLOD(gsamplerCube sampler, vec3 P);
vec2 textureQueryLOD(gsampler1DArray sampler, float P);
vec2 textureQueryLOD(gsampler2DArray sampler, vec2 P);
vec2 textureQueryLOD(gsamplerCubeArray sampler, vec3 P);
vec2 textureQueryLOD(sampler1DShadow sampler, float P);
vec2 textureQueryLOD(sampler2DShadow sampler, vec2 P);
vec2 textureQueryLOD(samplerCubeShadow sampler, vec3 P);
vec2 textureQueryLOD(sampler1DArrayShadow sampler, float P);
vec2 textureQueryLOD(sampler2DArrayShadow sampler, vec2 P);
vec2 textureQueryLOD(samplerCubeArrayShadow sampler, vec3 P);

@ glsl>=430 ext:GL_ARB_texture_query_levels
int textureQueryLevels(gsampler1D sampler);
int textureQueryLevels(gsampler2D sampler);
int textureQueryLevels(gsampler3D sampler);
int textureQueryLevels(gsamplerCube sampler);
int textureQueryLevels(gsampler1DArray sampler);
int textureQueryLevels(gsampler2DArray sampler);
int textureQueryLevels(gsamplerCubeArray sampler);
int textureQueryLevels(sampler1DShadow sampler);
int textureQueryLevels(sampler2DShadow sampler);
int textureQueryLevels(samplerCubeShadow sampler);
int textureQueryLevels(sampler1DArrayShadow sampler);
int textureQueryLevels(sampler2DArrayShadow sampler);
int textureQueryLevels(samplerCubeArrayShadow sampler);

@ glsl>=450 ext:GL_ARB_shader_texture_image_samples
int textureSamples(gsampler2DMS sampler);
int textureSamples(gsampler2DMSArray sampler);

// ---- 8.9.2 texel lookup functions
@ glsl>=130 es>=300 ext:GL_EXT_gpu_shader4
gvec4 texture(gsampler1D sampler, float P);
gvec4 texture(gsampler1D sampler, float P, float bias);
gvec4 texture(gsampler2D sampler, vec2 P);
gvec4 texture(gsampler2D sampler, vec2 P, float bias);
gvec4 texture(gsampler3D sampler, vec3 P);
gvec4 texture(gsampler3D sampler, vec3 P, float bias);
gvec4 texture(gsamplerCube sampler, vec3 P);
gvec4 texture(gsamplerCube sampler, vec3 P, float bias);
float texture(sampler1DShadow sampler, vec3 P);
float texture(sampler1DShadow sampler, vec3 P, float bias);
float texture(sampler2DShadow sampler, vec3 P);
float texture(sampler2DShadow sampler, vec3 P, float bias);
float texture(samplerCubeShadow sampler, vec4 P);
float texture(samplerCubeShadow sampler, vec4 P, float bias);
gvec4 texture(gsampler1DArray sampler, vec2 P);
gvec4 texture(gsampler1DArray sampler, vec2 P, float bias);
gvec4 texture(gsampler2DArray sampler, vec3 P);
gvec4 texture(gsampler2DArray sampler, vec3 P, float bias);
gvec4 texture(gsamplerCubeArray sampler, vec4 P);
gvec4 texture(gsamplerCubeArray sampler, vec4 P, float bias);
float texture(sampler1DArrayShadow sampler, vec3 P);
float texture(sampler1DArrayShadow sampler, vec3 P, float bias);
float texture(sampler2DArrayShadow sampler, vec4 P);
gvec4 texture(gsampler2DRect sampler, vec2 P);
float texture(sampler2DRectShadow sampler, vec3 P);
float texture(samplerCubeArrayShadow sampler, vec4 P, float compare);
gvec4 textureProj(gsampler1D sampler, vec2 P);
gvec4 textureProj(gsampler1D sampler, vec2 P, float bias);
gvec4 textureProj(gsampler1D sampler, vec4 P);
gvec4 textureProj(gsampler1D sampler, vec4 P, float bias);
gvec4 textureProj(gsampler2D sampler, vec3 P);
gvec4 textureProj(gsampler2D sampler, vec3 P, float bias);
gvec4 textureProj(gsampler2D sampler, vec4 P);
gvec4 textureProj(gsampler2D sampler, vec4 P, float bias);
gvec4 textureProj(gsampler3D sampler, vec4 P);
gvec4 textureProj(gsampler3D sampler, vec4 P, float bias);
float textureProj(sampler1DShadow sampler, vec4 P);
float textureProj(sampler1DShadow sampler, vec4 P, float bias);
float textureProj(sampler2DShadow sampler, vec4 P);
float textureProj(sampler2DShadow sampler, vec4 P, float bias);
gvec4 textureProj(gsampler2DRect sampler, vec3 P);
gvec4 textureProj(gsampler2DRect sampler, vec4 P);
float textureProj(sampler2DRectShadow sampler, vec4 P);
gvec4 textureLod(gsampler1D sampler, float P, float lod);
gvec4 textureLod(gsampler2D sampler, vec2 P, float lod);
gvec4 textureLod(gsampler3D sampler, vec3 P, float lod);
gvec4 textureLod(gsamplerCube sampler, vec3 P, float lod);
float textureLod(sampler1DShadow sampler, vec3 P, float lod);
float textureLod(sampler2DShadow sampler, vec3 P, float lod);
gvec4 textureLod(gsampler1DArray sampler, vec2 P, float lod);
gvec4 textureLod(gsampler2DArray sampler, vec3 P, float lod);
float textureLod(sampler1DArrayShadow sampler, vec3 P, float lod);
gvec4 textureLod(gsamplerCubeArray sampler, vec4 P, float lod);
gvec4 textureOffset(gsampler1D sampler, float P, int offset);
gvec4 textureOffset(gsampler1D sampler, float P, int offset, float bias);
gvec4 textureOffset(gsampler2D sampler, vec2 P, ivec2 offset);
gvec4 textureOffset(gsampler2D sampler, vec2 P, ivec2 offset, float bias);
gvec4 textureOffset(gsampler3D sampler, vec3 P, ivec3 offset);
gvec4 textureOffset(gsampler3D sampler, vec3 P, ivec3 offset, float bias);
float textureOffset(sampler1DShadow sampler, vec3 P, int offset);
float textureOffset(sampler1DShadow sampler, vec3 P, int offset, float bias);
float textureOffset(sampler2DShadow sampler, vec3 P, ivec2 offset);
float textureOffset(sampler2DShadow sampler, vec3 P, ivec2 offset, float bias);
gvec4 textureOffset(gsampler1DArray sampler, vec2 P, int offset);
gvec4 textureOffset(gsampler1DArray sampler, vec2 P, int offset, float bias);
gvec4 textureOffset(gsampler2DArray sampler, vec3 P, ivec2 offset);
gvec4 textureOffset(gsampler2DArray sampler, vec3 P, ivec2 offset, float bias);
float textureOffset(sampler1DArrayShadow sampler, vec3 P, int offset);
float textureOffset(sampler1DArrayShadow sampler, vec3 P, int offset, float bias);
float textureOffset(sampler2DArrayShadow sampler, vec4 P, ivec2 offset);
gvec4 textureOffset(gsampler2DRect sampler, vec2 P, ivec2 offset);
float textureOffset(sampler2DRectShadow sampler, vec3 P, ivec2 offset);
gvec4 texelFetch(gsampler1D sampler, int P, int lod);
gvec4 texelFetch(gsampler2D sampler, ivec2 P, int lod);
gvec4 texelFetch(gsampler3D sampler, ivec3 P, int lod);
gvec4 texelFetch(gsampler2DRect sampler, ivec2 P);
gvec4 texelFetch(gsampler1DArray sampler, ivec2 P, int lod);
gvec4 texelFetch(gsampler2DArray sampler, ivec3 P, int lod);
gvec4 texelFetch(gsamplerBuffer sampler, int P);
gvec4 texelFetch(gsampler2DMS sampler, ivec2 P, int sampleIndex);
gvec4 texelFetch(gsampler2DMSArray sampler, ivec3 P, int sampleIndex);
gvec4 texelFetchOffset(gsampler1D sampler, int P, int lod, int offset);
gvec4 texelFetchOffset(gsampler2D sampler, ivec2 P, int lod, ivec2 offset);
gvec4 texelFetchOffset(gsampler3D sampler, ivec3 P, int lod, ivec3 offset);
gvec4 texelFetchOffset(gsampler2DRect sampler, ivec2 P, ivec2 offset);
gvec4 texelFetchOffset(gsampler1DArray sampler, ivec2 P, int lod, int offset);
gvec4 texelFetchOffset(gsampler2DArray sampler, ivec3 P, int lod, ivec2 offset);
gvec4 textureProjOffset(gsampler1D sampler, vec2 P, int offset);
gvec4 textureProjOffset(gsampler1D sampler, vec2 P, int offset, float bias);
gvec4 textureProjOffset(gsampler1D sampler, vec4 P, int offset);
gvec4 textureProjOffset(gsampler1D sampler, vec4 P, int offset, float bias);
gvec4 textureProjOffset(gsampler2D sampler, vec3 P, ivec2 offset);
gvec4 textureProjOffset(gsampler2D sampler, vec3 P, ivec2 offset, float bias);
gvec4 textureProjOffset(gsampler2D sampler, vec4 P, ivec2 offset);
gvec4 textureProjOffset(gsampler2D sampler, vec4 P, ivec2 offset, float bias);
gvec4 textureProjOffset(gsampler3D sampler, vec4 P, ivec3 offset);
gvec4 textureProjOffset(gsampler3D sampler, vec4 P, ivec3 offset, float bias);
float textureProjOffset(sampler1DShadow sampler, vec4 P, int offset);
float textureProjOffset(sampler1DShadow sampler, vec4 P, int offset, float bias);
float textureProjOffset(sampler2DShadow sampler, vec4 P, ivec2 offset);
float textureProjOffset(sampler2DShadow sampler, vec4 P, ivec2 offset, float bias);
gvec4 textureProjOffset(gsampler2DRect sampler, vec3 P, ivec2 offset);
gvec4 textureProjOffset(gsampler2DRect sampler, vec4 P, ivec2 offset);
float textureProjOffset(sampler2DRectShadow sampler, vec4 P, ivec2 offset);
gvec4 textureLodOffset(gsampler1D sampler, float P, float lod, int offset);
gvec4 textureLodOffset(gsampler2D sampler, vec2 P, float lod, ivec2 offset);
gvec4 textureLodOffset(gsampler3D sampler, vec3 P, float lod, ivec3 offset);
float textureLodOffset(sampler1DShadow sampler, vec3 P, float lod, int offset);
float textureLodOffset(sampler2DShadow sampler, vec3 P, float lod, ivec2 offset);
gvec4 textureLodOffset(gsampler1DArray sampler, vec2 P, float lod, int offset);
gvec4 textureLodOffset(gsampler2DArray sampler, vec3 P, float lod, ivec2 offset);
float textureLodOffset(sampler1DArrayShadow sampler, vec3 P, float lod, int offset);
gvec4 textureProjLod(gsampler1D sampler, vec2 P, float lod);
gvec4 textureProjLod(gsampler1D sampler, vec4 P, float lod);
gvec4 textureProjLod(gsampler2D sampler, vec3 P, float lod);
gvec4 textureProjLod(gsampler2D sampler, vec4 P, float lod);
gvec4 textureProjLod(gsampler3D sampler, vec4 P, float lod);
float textureProjLod(sampler1DShadow sampler, vec4 P, float lod);
float textureProjLod(sampler2DShadow sampler, vec4 P, float lod);
gvec4 textureProjLodOffset(gsampler1D sampler, vec2 P, float lod, int offset);
gvec4 textureProjLodOffset(gsampler1D sampler, vec4 P, float lod, int offset);
gvec4 textureProjLodOffset(gsampler2D sampler, vec3 P, float lod, ivec2 offset);
gvec4 textureProjLodOffset(gsampler2D sampler, vec4 P, float lod, ivec2 offset);
gvec4 textureProjLodOffset(gsampler3D sampler, vec4 P, float lod, ivec3 offset);
float textureProjLodOffset(sampler1DShadow sampler, vec4 P, float lod, int offset);
float textureProjLodOffset(sampler2DShadow sampler, vec4 P, float lod, ivec2 offset);
gvec4 textureGrad(gsampler1D sampler, float P, float dPdx, float dPdy);
gvec4 textureGrad(gsampler2D sampler, vec2 P, vec2 dPdx, vec2 dPdy);
gvec4 textureGrad(gsampler3D sampler, vec3 P, vec3 dPdx, vec3 dPdy);
gvec4 textureGrad(gsamplerCube sampler, vec3 P, vec3 dPdx, vec3 dPdy);
gvec4 textureGrad(gsampler2DRect sampler, vec2 P, vec2 dPdx, vec2 dPdy);
float textureGrad(sampler2DRectShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy);
float textureGrad(sampler1DShadow sampler, vec3 P, float dPdx, float dPdy);
float textureGrad(sampler2DShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy);
float textureGrad(samplerCubeShadow sampler, vec4 P, vec3 dPdx, vec3 dPdy);
gvec4 textureGrad(gsampler1DArray sampler, vec2 P, float dPdx, float dPdy);
gvec4 textureGrad(gsampler2DArray sampler, vec3 P, vec2 dPdx, vec2 dPdy);
float textureGrad(sampler1DArrayShadow sampler, vec3 P, float dPdx, float dPdy);
float textureGrad(sampler2DArrayShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy);
gvec4 textureGrad(gsamplerCubeArray sampler, vec4 P, vec3 dPdx, vec3 dPdy);
gvec4 textureGradOffset(gsampler1D sampler, float P, float dPdx, float dPdy, int offset);
gvec4 textureGradOffset(gsampler2D sampler, vec2 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureGradOffset(gsampler3D sampler, vec3 P, vec3 dPdx, vec3 dPdy, ivec3 offset);
gvec4 textureGradOffset(gsampler2DRect sampler, vec2 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
float textureGradOffset(sampler2DRectShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
float textureGradOffset(sampler1DShadow sampler, vec3 P, float dPdx, float dPdy, int offset);
float textureGradOffset(sampler2DShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureGradOffset(gsampler1DArray sampler, vec2 P, float dPdx, float dPdy, int offset);
gvec4 textureGradOffset(gsampler2DArray sampler, vec3 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
float textureGradOffset(sampler1DArrayShadow sampler, vec3 P, float dPdx, float dPdy, int offset);
float textureGradOffset(sampler2DArrayShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureProjGrad(gsampler1D sampler, vec2 P, float dPdx, float dPdy);
gvec4 textureProjGrad(gsampler1D sampler, vec4 P, float dPdx, float dPdy);
gvec4 textureProjGrad(gsampler2D sampler, vec3 P, vec2 dPdx, vec2 dPdy);
gvec4 textureProjGrad(gsampler2D sampler, vec4 P, vec2 dPdx, vec2 dPdy);
gvec4 textureProjGrad(gsampler3D sampler, vec4 P, vec3 dPdx, vec3 dPdy);
gvec4 textureProjGrad(gsampler2DRect sampler, vec3 P, vec2 dPdx, vec2 dPdy);
gvec4 textureProjGrad(gsampler2DRect sampler, vec4 P, vec2 dPdx, vec2 dPdy);
float textureProjGrad(sampler2DRectShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy);
float textureProjGrad(sampler1DShadow sampler, vec4 P, float dPdx, float dPdy);
float textureProjGrad(sampler2DShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy);
gvec4 textureProjGradOffset(gsampler1D sampler, vec2 P, float dPdx, float dPdy, int offset);
gvec4 textureProjGradOffset(gsampler1D sampler, vec4 P, float dPdx, float dPdy, int offset);
gvec4 textureProjGradOffset(gsampler2D sampler, vec3 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureProjGradOffset(gsampler2D sampler, vec4 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureProjGradOffset(gsampler3D sampler, vec4 P, vec3 dPdx, vec3 dPdy, ivec3 offset);
gvec4 textureProjGradOffset(gsampler2DRect sampler, vec3 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
gvec4 textureProjGradOffset(gsampler2DRect sampler, vec4 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
float textureProjGradOffset(sampler2DRectShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy, ivec2 offset);
float textureProjGradOffset(sampler1DShadow sampler, vec4 P, float dPdx, float dPdy, int offset);
float textureProjGradOffset(sampler2DShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy, ivec2 offset);

// ---- 8.9.4 texture gather functions
@ glsl>=400 es>=310 ext:GL_ARB_texture_gather ext:GL_ARB_gpu_shader5
gvec4 textureGather(gsampler2D sampler, vec2 P);
gvec4 textureGather(gsampler2D sampler, vec2 P, int comp);
gvec4 textureGather(gsampler2DArray sampler, vec3 P);
gvec4 textureGather(gsampler2DArray sampler, vec3 P, int comp);
gvec4 textureGather(gsamplerCube sampler, vec3 P);
gvec4 textureGather(gsamplerCube sampler, vec3 P, int comp);
gvec4 textureGather(gsamplerCubeArray sampler, vec4 P);
gvec4 textureGather(gsamplerCubeArray sampler, vec4 P, int comp);
gvec4 textureGather(gsampler2DRect sampler, vec2 P);
gvec4 textureGather(gsampler2DRect sampler, vec2 P, int comp);
vec4 textureGather(sampler2DShadow sampler, vec2 P, float refZ);
vec4 textureGather(sampler2DArrayShadow sampler, vec3 P, float refZ);
vec4 textureGather(samplerCubeShadow sampler, vec3 P, float refZ);
vec4 textureGather(samplerCubeArrayShadow sampler, vec4 P, float refZ);
vec4 textureGather(sampler2DRectShadow sampler, vec2 P, float refZ);
gvec4 textureGatherOffset(gsampler2D sampler, vec2 P, ivec2 offset);
gvec4 textureGatherOffset(gsampler2D sampler, vec2 P, ivec2 offset, int comp);
gvec4 textureGatherOffset(gsampler2DArray sampler, vec3 P, ivec2 offset);
gvec4 textureGatherOffset(gsampler2DArray sampler, vec3 P, ivec2 offset, int comp);
gvec4 textureGatherOffset(gsampler2DRect sampler, vec2 P, ivec2 offset);
gvec4 textureGatherOffset(gsampler2DRect sampler, vec2 P, ivec2 offset, int comp);
vec4 textureGatherOffset(sampler2DShadow sampler, vec2 P, float refZ, ivec2 offset);
vec4 textureGatherOffset(sampler2DArrayShadow sampler, vec3 P, float refZ, ivec2 offset);
vec4 textureGatherOffset(sampler2DRectShadow sampler, vec2 P, float refZ, ivec2 offset);
gvec4 textureGatherOffsets(gsampler2D sampler, vec2 P, ivec2[4] offsets);
gvec4 textureGatherOffsets(gsampler2D sampler, vec2 P, ivec2[4] offsets, int comp);
gvec4 textureGatherOffsets(gsampler2DArray sampler, vec3 P, ivec2[4] offsets);
gvec4 textureGatherOffsets(gsampler2DArray sampler, vec3 P, ivec2[4] offsets, int comp);
gvec4 textureGatherOffsets(gsampler2DRect sampler, vec2 P, ivec2[4] offsets);
gvec4 textureGatherOffsets(gsampler2DRect sampler, vec2 P, ivec2[4] offsets, int comp);
vec4 textureGatherOffsets(sampler2DShadow sampler, vec2 P, float refZ, ivec2[4] offsets);
vec4 textureGatherOffsets(sampler2DArrayShadow sampler, vec3 P, float refZ, ivec2[4] offsets);
vec4 textureGatherOffsets(sampler2DRectShadow sampler, vec2 P, float refZ, ivec2[4] offsets);

// ---- 8.9.5 compatibility profile texture functions
// these are also available in the core profile before 4.20
@ glsl>=110 glsl<420
vec4 texture1D(sampler1D sampler, float coord);
vec4 texture1D(sampler1D sampler, float coord, float bias);
vec4 texture1DProj(sampler1D sampler, vec2 coord);
vec4 texture1DProj(sampler1D sampler, vec2 coord, float bias);
vec4 texture1DProj(sampler1D sampler, vec4 coord);
vec4 texture1DProj(sampler1D sampler, vec4 coord, float bias);
vec4 texture1DLod(sampler1D sampler, float coord, float lod);
vec4 texture1DProjLod(sampler1D sampler, vec2 coord, float lod);
vec4 texture1DProjLod(sampler1D sampler, vec4 coord, float lod);
vec4 texture3D(sampler3D sampler, vec3 coord);
vec4 texture3D(sampler3D sampler, vec3 coord, float bias);
vec4 texture3DProj(sampler3D sampler, vec4 coord);
vec4 texture3DProj(sampler3D sampler, vec4 coord, float bias);
vec4 texture3DLod(sampler3D sampler, vec3 coord, float lod);
vec4 texture3DProjLod(sampler3D sampler, vec4 coord, float lod);
vec4 shadow1D(sampler1DShadow sampler, vec3 coord);
vec4 shadow1D(sampler1DShadow sampler, vec3 coord, float bias);
vec4 shadow2D(sampler2DShadow sampler, vec3 coord);
vec4 shadow2D(sampler2DShadow sampler, vec3 coord, float bias);
vec4 shadow1DProj(sampler1DShadow sampler, vec4 coord);
vec4 shadow1DProj(sampler1DShadow sampler, vec4 coord, float bias);
vec4 shadow2DProj(sampler2DShadow sampler, vec4 coord);
vec4 shadow2DProj(sampler2DShadow sampler, vec4 coord, float bias);
vec4 shadow1DLod(sampler1DShadow sampler, vec3 coord, float lod);
vec4 shadow2DLod(sampler2DShadow sampler, vec3 coord, float lod);
vec4 shadow1DProjLod(sampler1DShadow sampler, vec4 coord, float lod);
vec4 shadow2DProjLod(sampler2DShadow sampler, vec4 coord, float lod);
vec4 texture2DRect(sampler2DRect sampler, vec2 coord);
vec4 texture2DRectProj(sampler2DRect sampler, vec3 coord);
vec4 texture2DRectProj(sampler2DRect sampler, vec4 coord);
vec4 shadow2DRect(sampler2DRectShadow sampler, vec3 coord);
vec4 shadow2DRectProj(sampler2DRectShadow sampler, vec4 coord);

// the functions that GLSL ES 1.00 has as well
@ glsl>=110 glsl<420 es>=100 es<300
vec4 texture2D(sampler2D sampler, vec2 coord);
vec4 texture2D(sampler2D sampler, vec2 coord, float bias);
vec4 texture2DProj(sampler2D sampler, vec3 coord);
vec4 texture2DProj(sampler2D sampler, vec3 coord, float bias);
vec4 texture2DProj(sampler2D sampler, vec4 coord);
vec4 texture2DProj(sampler2D sampler, vec4 coord, float bias);
vec4 texture2DLod(sampler2D sampler, vec2 coord, float lod);
vec4 texture2DProjLod(sampler2D sampler, vec3 coord, float lod);
vec4 texture2DProjLod(sampler2D sampler, vec4 coord, float lod);
vec4 textureCube(samplerCube sampler, vec3 coord);
vec4 textureCube(samplerCube sampler, vec3 coord, float bias);
vec4 textureCubeLod(samplerCube sampler, vec3 coord, float lod);

// ---- texture functions of extensions
@ ext:GL_ARB_shader_texture_lod
vec4 texture1DGradARB(sampler1D sampler, float P, float dPdx, float dPdy);
vec4 texture1DProjGradARB(sampler1D sampler, vec2 P, float dPdx, float dPdy);
vec4 texture1DProjGradARB(sampler1D sampler, vec4 P, float dPdx, float dPdy);
vec4 texture2DGradARB(sampler2D sampler, vec2 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DProjGradARB(sampler2D sampler, vec3 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DProjGradARB(sampler2D sampler, vec4 P, vec2 dPdx, vec2 dPdy);
vec4 texture3DGradARB(sampler3D sampler, vec3 P, vec3 dPdx, vec3 dPdy);
vec4 texture3DProjGradARB(sampler3D sampler, vec4 P, vec3 dPdx, vec3 dPdy);
vec4 textureCubeGradARB(samplerCube sampler, vec3 P, vec3 dPdx, vec3 dPdy);
vec4 shadow1DGradARB(sampler1DShadow sampler, vec3 P, float dPdx, float dPdy);
vec4 shadow1DProjGradARB(sampler1DShadow sampler, vec4 P, float dPdx, float dPdy);
vec4 shadow2DGradARB(sampler2DShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy);
vec4 shadow2DProjGradARB(sampler2DShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DRectGradARB(sampler2DRect sampler, vec2 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DRectProjGradARB(sampler2DRect sampler, vec3 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DRectProjGradARB(sampler2DRect sampler, vec4 P, vec2 dPdx, vec2 dPdy);
vec4 shadow2DRectGradARB(sampler2DRectShadow sampler, vec3 P, vec2 dPdx, vec2 dPdy);
vec4 shadow2DRectProjGradARB(sampler2DRectShadow sampler, vec4 P, vec2 dPdx, vec2 dPdy);

@ ext:GL_EXT_shader_texture_lod
vec4 texture2DLodEXT(sampler2D sampler, vec2 coord, float lod);
vec4 texture2DProjLodEXT(sampler2D sampler, vec3 coord, float lod);
vec4 texture2DProjLodEXT(sampler2D sampler, vec4 coord, float lod);
vec4 textureCubeLodEXT(samplerCube sampler, vec3 coord, float lod);
vec4 texture2DGradEXT(sampler2D sampler, vec2 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DProjGradEXT(sampler2D sampler, vec3 P, vec2 dPdx, vec2 dPdy);
vec4 texture2DProjGradEXT(sampler2D sampler, vec4 P, vec2 dPdx, vec2 dPdy);
vec4 textureCubeGradEXT(samplerCube sampler, vec3 P, vec3 dPdx, vec3 dPdy);

@ ext:GL_OES_texture_3D
vec4 texture3D(sampler3D sampler, vec3 coord);
vec4 texture3D(sampler3D sampler, vec3 coord, float bias);
vec4 texture3DProj(sampler3D sampler, vec4 coord);
vec4 texture3DProj(sampler3D sampler, vec4 coord, float bias);
vec4 texture3DLod(sampler3D sampler, vec3 coord, float lod);
vec4 texture3DProjLod(sampler3D sampler, vec4 coord, float lod);
