package io.github.douira.glsl_transformer.ast.print;

public class OutputOptions {
  private boolean printInfo;
  private String headerSuffix;

  public OutputOptions() {
    this.printInfo = false;
    this.headerSuffix = null;
  }

  public OutputOptions(boolean printLibraryVersionInfo, String headerSuffix) {
    this.printInfo = printLibraryVersionInfo;
    this.headerSuffix = headerSuffix;
  }

  public void enablePrintInfo() {
    printInfo = true;
  }

  public void disablePrintInfo() {
    printInfo = false;
  }

  public void setHeaderSuffix(String headerSuffix) {
    this.headerSuffix = headerSuffix;
  }

  public String getPrintHeader() {
    if (printInfo || headerSuffix != null) {
      return "// Generated by glsl-transformer" +
          (headerSuffix == null ? "" : " " + headerSuffix) + "\n";
    }
    return null;
  }

  public OutputOptions clone() {
    return new OutputOptions(printInfo, headerSuffix);
  }
}
